#默认使用配置
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yang?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  #type-AliasesPackage: com.neu.yang.entity
  #mapper-locations: classpath*:mapper/*.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.neu.yang.entity
server:
  port: 8080

  spring:
    freemarker:
      request-context-attribute: req  #req访问request
      suffix: .html  #后缀名
      content-type: text/html
      enabled: true
      cache: false #缓存配置
      template-loader-path: classpath:/templates/ #模板加载路径 按需配置
      charset: UTF-8 #编码格式
      settings:
        number_format: '0.##'   #数字格式化，无小数点
